### ISSUE TITLE
Introduction Video

### ISSUE THREAD

**Issue by JonHerke-TG** [AdvitDeepak/transcript-analysis#1]
It would be great to have an introduction video to walk users through the project in more details! (3 - 5 mins)... ALSO awesome project! Let me know when we should start sharing on Social Media and in the TigerGraph community!!

**Comment by AdvitDeepak** [comment]
Ahh, thank you! Sounds good, will do 😁. Should be ready to go after the holidays! 🥳

**Comment by JonHerke-TG** [comment]
A couple of other students are interested in helping out... so thought video could get them up to speed.

**Comment by JonHerke-TG** [comment]
![image](https://user-images.githubusercontent.com/58706839/147173430-8c982762-16af-440f-be2d-4f428b1962fc.png)

**Comment by AdvitDeepak** [comment]
Found some time to record/publish a [brief intro video](https://www.youtube.com/watch?v=8v3k_1K4B_Y) (ended up being a little longer than expected 😅).
Additionally, if the students would like to get in touch regarding this program, they can always feel free to reach out!
